#This file is used to set the names and house and unit codes of X10 devices
#use this format for devices:
#:devices:
#  :firstdevicename: A5
#  :anotherdevice: B1
#  :alarm: B2
#
#case matters for names, not for house codes
#
# available options:
# :hostname # ip/hostname of mochad server (default localhost)
# :hostport # port of mochad server (default 1099)
# :rf       # set true to use radiofrency, set false to use powerline (default true)
# :urls     # the urls to read statuses from
# :devices  # list the device nicknames and locations

:hostname: localhost

:urls:
  - http://jenkins.conviocloud.com/view/COM/job/eCRM-Trunk-junit:
    :devices:
      :passing: A2
      :failing: A1

  - http://jenkins.conviocloud.com/view/Mordor Patch Build View:
    :devices:
      :passing: A3
      :failing: A4
